seml:
  executable: seml/sciplex2_script.py
  name: cpa_hyperparam
  output_dir: seml/logs
  project_root_dir: /storage/groups/ml01/workspace/carlo.dedonno/cpa-reproducibility
  conda_environment: cpa_2
slurm:
  experiments_per_job: 1
  sbatch_options_template: GPU
  sbatch_options:
    mem: 50G          # memory
    cpus-per-task: 6  # num cores
    time: 1-00:01     # max time, D-HH:MM
    nice: 10000
  max_simultaneous_jobs: 6

fixed:
  adata_path: /storage/groups/ml01/workspace/carlo.dedonno/cpa-reproducibility/datasets/GSM_new.h5ad
  save_dir: /storage/groups/ml01/workspace/carlo.dedonno/cpa-reproducibility/sweep_models/sciplex2
  max_epochs: 1000
  max_minutes: 120
  checkpoint_freq: 50
  run_eval: True
  perturbation_key: condition
  covariate_keys: cell_type #not sure how to specify a list of covs in YAML
  dose_key: dose_val
  split_key: split
  loss_ae: gauss
  patience: 20

grid:
  doser_type:
    type: choice
    options:
      - mlp
      - logsigm
  decoder_activation:
    type: choice
    options: 
      - linear
      - ReLU

random:
  samples: 200
  seed: 42
  batch_size:
    type: choice
    options:
      - 128
      - 256
  step_size_lr:
    type: uniform
    min: 10
    max: 100
  #AUTOENCODER PARAMS
  #latent dimension
  dim:            
    type: choice
    options:
      - 32
      - 64
      - 128
      - 256
  #width of ae layers
  autoencoder_width: 
    type: choice
    options:
      - 64
      - 128
      - 256
      - 512
  #no. of ae layers
  autoencoder_depth:
    type: choice
    options:
      - 2
      - 3
      - 4
  #learning rate of ae
  autoencoder_lr: 
    type: loguniform
    min: 1e-4
    max: 1e-2

  #weight decay of ae
  autoencoder_wd: 
    type: loguniform
    min: 1e-8
    max: 1e-6

  #ADVERSARY CLF PARAMS
  #width of layers
  adversary_width: 
    type: choice
    options:
      - 64
      - 128
  #no. of layers
  adversary_depth:
    type: choice
    options: 
      - 1
      - 2
      - 3
  #learning rate
  adversary_lr: 
    type: loguniform
    min: 1e-4
    max: 1e-2
  #weight decay
  adversary_wd:
    type: loguniform
    min: 1e-8
    max: 1e-6
  #how many steps backprop through clfs
  adversary_steps:
    type: choice
    options:
      - 3
      - 5
      - 10
  #regularization term
  reg_adversary:
    type: uniform
    min: 1
    max: 100
  #penalty term ???
  penalty_adversary:
    type: uniform
    min: 1
    max: 100

  #DOSERS PARAMS
  #width of dosers layers
  dosers_width: 
    type: choice
    options:
      - 64
      - 128
  #no. of dosers layers
  dosers_depth:
    type: choice
    options: 
      - 1
      - 2
      - 3
      - 4
  #learning rate of dosers
  dosers_lr: 
    type: loguniform
    min: 1e-4
    max: 1e-2
  #weight decay of dosers
  dosers_wd:
    type: loguniform
    min: 1e-8
    max: 1e-6